const data=[
    {
user:"Nikita",
postImage:"https://www.pexels.com/photo/close-up-shot-of-a-yellow-flower-bouquet-10922468/",
Likes:"21",
Timestamp:"2d"
    },
    {
    user:"Neha",
postImage:"https://www.pexels.com/photo/taxis-in-front-of-palace-in-istanbul-17554347/",
Likes:"33",
Timestamp:"3d"
    },
    {
        user:"Nancy",
    postImage:"https://www.pexels.com/photo/young-woman-in-a-pink-suit-sitting-in-a-room-with-blue-lighting-18421849/",
    Likes:"44",
    Timestamp:"4d"
        },
            {
    user:"Payal",
postImage:"https://www.pexels.com/photo/white-eggs-beside-yellow-tulips-10874333/",
Likes:"22",
Timestamp:"1d"
    },
    {
        user:"Garima",
    postImage:"https://www.pexels.com/photo/20574181/",
    Likes:"22",
    Timestamp:"3d"
        },
        {
            user:"Kajal",
        postImage:"https://www.pexels.com/photo/white-eggs-beside-yellow-tulips-10874333/",
        Likes:"44",
        Timestamp:"3d"
            },      
            {
                user:"Disha",
            postImage:"https://www.pexels.com/photo/smiley-face-and-good-morning-text-painted-on-a-foggy-window-18781624/",
            Likes:"77",
            Timestamp:"7d"
                },
                {
                    user:"Tannu",
                postImage:"https://www.pexels.com/photo/pink-car-19294343/",
                Likes:"44",
                Timestamp:"3d"
                    },
                    {
                        user:"Riya",
                    postImage:"https://www.pexels.com/photo/close-up-shot-of-easter-eggs-on-an-egg-tray-7381200/",
                    Likes:"33",
                    Timestamp:"2d"
                        }                                                     
]
